apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: ping-source-consumer-pipe
spec:
  source:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: kamelet-sink
    properties:
      type: dev.knative.sources.ping
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
